name: CI

on: [push, pull_request]

jobs:
  commitlint:
    name: Commit lint
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git
          npm install -g pnpm
      - name: Install commitlint
        run: |
          pnpm add conventional-changelog-conventionalcommits -w
          pnpm add commitlint@latest -w
      - name: Validate current commit
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commit
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  chromatic-deployment:
    name: Storybook Chromatic Deployment
    needs: [commitlint]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
        working-directory: apps/design-system
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: apps/design-system
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
